-- ============================================================
-- TechLog · update to v1.07.86
-- Нумерация документов и имён файлов «конструктором».
--   jobs.no / placements.no — сквозные порядковые номера, как у
--     пропозалов (proposals.no). Существующим строкам номера
--     раздаются при добавлении колонки, дальше их выдаёт сервер.
--   org_settings.doc_no_fmt   — шаблон номера документа
--   org_settings.file_name_fmt— шаблон имени файла на Диске
--   org_settings.doc_no_pad   — сколько знаков в порядковом номере
-- Идемпотентно: повторный запуск безопасен, данные не трогаются.
-- ============================================================
alter table public.jobs
  add column if not exists no bigint generated by default as identity;
create unique index if not exists jobs_no_idx on public.jobs(no);

alter table public.placements
  add column if not exists no bigint generated by default as identity;
create unique index if not exists placements_no_idx on public.placements(no);

alter table public.org_settings
  add column if not exists doc_no_fmt    text not null default '{TYPE}-{DATE}-{CX}-{UNIT}-{SEQ}',
  add column if not exists file_name_fmt text not null default '{DATE}_{CX}_{UNIT}_{NAME}_{SEQ}',
  add column if not exists doc_no_pad    int  not null default 5;

alter table public.org_settings drop constraint if exists org_doc_pad_ck;
alter table public.org_settings add constraint org_doc_pad_ck
  check (doc_no_pad between 1 and 9);

-- строка настроек существует и на старых базах
insert into public.org_settings (id) values ('org') on conflict (id) do nothing;
