-- ============================================================
-- TechLog · update to v1.08.23
-- ДОКУМЕНТ РЕМОНТНЫХ РАБОТ (REP) — отделка после демонтажа.
--   repairs               — сам документ: работы, материалы, апрув, история
--   jobs.needs_repair     — ручной флаг «требуется восстановление»
--   extra_works.repair    — позиция справочника относится к ремонту
--   org_settings.rep_*    — кто создаёт и видно ли суммы работникам
-- Создавать документ может любая роль; апрув ставит админ (и менеджер,
-- если ему это разрешено в настройках). Правка одобренного документа
-- снимает апрув — это делает приложение, здесь только хранение истории.
-- Идемпотентно: повторный запуск безопасен.
-- ============================================================

-- ---------------------------------------------------------------------
-- 1. Документ
-- ---------------------------------------------------------------------
create table if not exists public.repairs (
  id              uuid primary key default gen_random_uuid(),
  no              bigint generated by default as identity,        -- номер REP-…
  date            date not null default current_date,
  counterparty_id uuid references public.counterparties(id) on delete set null,
  complex_id      uuid references public.complexes(id) on delete set null,
  unit_number     text not null default '',
  job_id          uuid references public.jobs(id)      on delete set null,
  proposal_id     uuid references public.proposals(id) on delete set null,
  helper_ids      jsonb not null default '[]'::jsonb,             -- бригада, как у jobs
  items           jsonb not null default '[]'::jsonb,             -- работы  [{q,code,d,d_en,a}]
  materials       jsonb not null default '[]'::jsonb,             -- материалы, та же форма
  note            text not null default '',
  note_en         text not null default '',
  po_number       text not null default '',
  complete_by     date,
  sales_tax       numeric not null default 0,
  freight         numeric not null default 0,
  total           numeric not null default 0,                     -- работы + материалы
  status          text not null default 'draft'
                  check (status in ('draft','sent','approved','declined')),
  hist            jsonb not null default '[]'::jsonb,             -- история апрува
  decline_reason  text not null default '',
  created_by      uuid references public.profiles(id) on delete set null,
  decided_by      uuid references public.profiles(id) on delete set null,
  decided_at      timestamptz,
  archived_at     timestamptz,
  archived_by     uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create unique index if not exists repairs_no_idx    on public.repairs(no);
create index if not exists repairs_job_idx          on public.repairs(job_id);
create index if not exists repairs_prop_idx         on public.repairs(proposal_id);
create index if not exists repairs_cx_idx           on public.repairs(complex_id, date desc);
create index if not exists repairs_date_idx         on public.repairs(date desc);
create index if not exists repairs_archived_idx     on public.repairs(archived_at);

-- ---------------------------------------------------------------------
-- 2. Флаг на работе и пометка позиций справочника
-- ---------------------------------------------------------------------
alter table public.jobs
  add column if not exists needs_repair boolean not null default false;

alter table public.extra_works
  add column if not exists repair boolean not null default false;

alter table public.org_settings
  add column if not exists rep_hide_prices boolean not null default false,
  add column if not exists rep_all_create  boolean not null default true;
insert into public.org_settings (id) values ('org') on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- 3. Права. Создаёт любой сотрудник — но только от своего имени.
--    Видят: админ и менеджер — всё; работник — свои документы и те,
--    что привязаны к видимой ему работе. Правят: админ, менеджер, автор.
--    Удаляет — только админ (у остальных документ уходит в архив).
-- ---------------------------------------------------------------------
alter table public.repairs enable row level security;

drop policy if exists rep_sel on public.repairs;
create policy rep_sel on public.repairs for select to authenticated
  using (
    public.my_role() in ('admin','manager')
    or created_by = auth.uid()
    or (job_id is not null and public.can_view_job(job_id))
  );

drop policy if exists rep_ins on public.repairs;
create policy rep_ins on public.repairs for insert to authenticated
  with check (created_by = auth.uid());

drop policy if exists rep_upd on public.repairs;
create policy rep_upd on public.repairs for update to authenticated
  using      (public.my_role() in ('admin','manager') or created_by = auth.uid())
  with check (public.my_role() in ('admin','manager') or created_by = auth.uid());

drop policy if exists rep_del on public.repairs;
create policy rep_del on public.repairs for delete to authenticated
  using (public.my_role() = 'admin');

-- ---------------------------------------------------------------------
-- 4. Апрув документа ремонта. Автор правит документ свободно — RLS ему
--    это разрешает, — поэтому статус стережёт триггер: поставить
--    «Одобрен»/«Отклонён» может только админ (и менеджер, если ему это
--    разрешено настройкой manager_can_approve). При восстановлении из
--    бэкапа проверка не мешает.
-- ---------------------------------------------------------------------
create or replace function public.repairs_guard()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_can boolean;
begin
  if coalesce(current_setting('techlog.restore', true), '') = '1' then return new; end if;
  select public.my_role() = 'admin'
      or (public.my_role() = 'manager'
          and coalesce((select manager_can_approve from public.org_settings where id = 'org'), false))
    into v_can;
  if TG_OP = 'INSERT' then
    if new.status in ('approved','declined') and not coalesce(v_can, false) then
      new.status := 'draft';
    end if;
    return new;
  end if;
  if new.status is distinct from old.status
     and new.status in ('approved','declined')
     and not coalesce(v_can, false) then
    raise exception 'FORBIDDEN_APPROVE';
  end if;
  return new;
end $$;

drop trigger if exists repairs_guard_t on public.repairs;
create trigger repairs_guard_t before insert or update on public.repairs
  for each row execute function public.repairs_guard();

-- ---------------------------------------------------------------------
-- 5. Справочник ремонтных работ. Позиции обычные — админ правит их
--    в «Справочники → Доп. работы», флаг repair поднимает их наверх
--    в подборе для документа ремонта. Цены ориентировочные: поставьте свои.
-- ---------------------------------------------------------------------
insert into public.extra_works (id, name, kind, needs_size, size_type_id, price, sort, code, repair) values
 ('c2000000-0000-4000-8000-000000000011','Установка гипсокартона / Drywall installation','work',false,null,85,11,'DRY',true),
 ('c2000000-0000-4000-8000-000000000012','Замена деревянных брусков / Wood studs replacement','work',false,null,45,12,'STD',true),
 ('c2000000-0000-4000-8000-000000000013','Восстановление ванны / Bathtub restoration','work',false,null,320,13,'TUB',true),
 ('c2000000-0000-4000-8000-000000000014','Восстановление стеновых панелей / Wall panel restoration','work',true,'c1000000-0000-4000-8000-000000000002',12,14,'PNL',true),
 ('c2000000-0000-4000-8000-000000000015','Установка дверной коробки / Door frame installation','work',false,null,190,15,'DRF',true),
 ('c2000000-0000-4000-8000-000000000016','Установка наличников / Door casing installation','work',true,'c1000000-0000-4000-8000-000000000001',6,16,'TRM',true),
 ('c2000000-0000-4000-8000-000000000017','Покраска после ремонта / Paint after repair','work',true,'c1000000-0000-4000-8000-000000000002',3,17,'PNT',true),
 ('c2000000-0000-4000-8000-000000000018','Покупка материалов / Materials purchase','purchase',false,null,0,18,'MAT',true)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- 6. Восстановление из бэкапа: документ ремонта тоже грузится.
-- ---------------------------------------------------------------------
create or replace function public.admin_restore_rows(p_table text, p_rows jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_allowed text[] := array[
    'profiles','counterparties','complexes','aux_equipment','work_types',
    'equipment_types','size_types','extra_works','product_types','price_list',
    'counterparty_prices','equipment_stock','org_settings','code_requests',
    'complex_code_history','hidden_staff','proposals','jobs','placements',
    'ext_requests','media','repairs'];
  v_cols text[]; v_collist text; v_set text; v_sql text;
  r jsonb; v_n int := 0; v_rc int;
  v_ins int := 0; v_skip int := 0; v_errs jsonb := '[]'::jsonb;
begin
  if public.my_role() is distinct from 'admin' then raise exception 'FORBIDDEN'; end if;
  if not (p_table = any(v_allowed)) then raise exception 'BAD_TABLE'; end if;
  if to_regclass('public.' || p_table) is null then raise exception 'NO_TABLE'; end if;
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
    return jsonb_build_object('inserted', 0, 'skipped', 0, 'errors', '[]'::jsonb);
  end if;

  perform set_config('techlog.restore', '1', true);

  select array_agg(quote_ident(column_name) order by ordinal_position) into v_cols
  from information_schema.columns
  where table_schema = 'public' and table_name = p_table
    and (p_rows->0) ? column_name;
  if v_cols is null then raise exception 'NO_MATCHING_COLUMNS'; end if;
  v_collist := array_to_string(v_cols, ',');

  if p_table = 'org_settings' then
    select string_agg(format('%s = excluded.%s', c, c), ', ')
      into v_set from unnest(v_cols) c where c <> 'id';
    v_sql := format(
      'insert into public.%I (%s) select %s from jsonb_populate_record(null::public.%I, $1)
       on conflict (id) do update set %s', p_table, v_collist, v_collist, p_table, v_set);
  else
    v_sql := format(
      'insert into public.%I (%s) select %s from jsonb_populate_record(null::public.%I, $1)
       on conflict do nothing', p_table, v_collist, v_collist, p_table);
  end if;

  for r in select * from jsonb_array_elements(p_rows) loop
    v_n := v_n + 1;
    begin
      execute v_sql using r;
      get diagnostics v_rc = row_count;
      if v_rc > 0 then v_ins := v_ins + 1; else v_skip := v_skip + 1; end if;
    exception when others then
      v_errs := v_errs || jsonb_build_object(
        'row', coalesce(r->>'id', '#' || v_n), 'error', sqlerrm);
    end;
  end loop;

  -- identity-счётчики номеров: после загрузки старых номеров двигаем вперёд
  if p_table in ('proposals','repairs') then
    execute format(
      'select setval(pg_get_serial_sequence(''public.%I'',''no''),
                     greatest((select coalesce(max(no), 0) from public.%I), 1), true)',
      p_table, p_table);
  end if;

  return jsonb_build_object('inserted', v_ins, 'skipped', v_skip, 'errors', v_errs);
end $$;
revoke all on function public.admin_restore_rows(text, jsonb) from public, anon;
grant execute on function public.admin_restore_rows(text, jsonb) to authenticated;

-- ---------------------------------------------------------------------
-- 7. Самопроверка
-- ---------------------------------------------------------------------
do $$
declare miss text := '';
begin
  if to_regclass('public.repairs') is null then miss := miss || ' repairs'; end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='jobs'
                   and column_name='needs_repair') then miss := miss || ' jobs.needs_repair'; end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='extra_works'
                   and column_name='repair') then miss := miss || ' extra_works.repair'; end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='org_settings'
                   and column_name='rep_hide_prices') then miss := miss || ' org_settings.rep_hide_prices'; end if;
  if to_regprocedure('public.repairs_guard()') is null
     then miss := miss || ' repairs_guard()'; end if;
  if not exists (select 1 from pg_trigger where tgname = 'repairs_guard_t'
                   and tgrelid = 'public.repairs'::regclass)
     then miss := miss || ' repairs_guard_t'; end if;
  if miss <> '' then
    raise warning 'TechLog 1.08.23: НЕ ХВАТАЕТ:%  — перезапустите скрипт целиком.', miss;
  else
    raise notice 'TechLog 1.08.23: документ ремонтных работ на месте.';
  end if;
end $$;

select 'TechLog v1.08.23 — скрипт выполнен.' as result;
