-- =====================================================================
-- TechLog update-to-1_07_27 — пропозалы, раздельный журнал,
-- согласование продлений сверх лимита
-- Выполнить целиком в Supabase → SQL Editor → Run. Повторный запуск безопасен
-- (перенос старых записей журнала выполнится один раз).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. ПРОПОЗАЛЫ (коммерческие предложения)
-- ---------------------------------------------------------------------
create table if not exists public.proposals (
  id              uuid primary key default gen_random_uuid(),
  no              bigint generated by default as identity,       -- номер P-…
  date            date not null default current_date,
  counterparty_id uuid references public.counterparties(id) on delete set null,
  complex_id      uuid references public.complexes(id) on delete set null,
  unit_number     text not null default '',
  note            text not null default '',
  items           jsonb not null default '[]'::jsonb,            -- [{d:'…', a:123}]
  total           numeric not null default 0,
  status          text not null default 'draft'
                  check (status in ('draft','sent','approved','declined')),
  created_by      uuid references public.profiles(id) on delete set null,
  decided_by      uuid references public.profiles(id) on delete set null,
  decided_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create unique index if not exists proposals_no_idx on public.proposals(no);
create index if not exists proposals_cx_idx   on public.proposals(complex_id, date desc);
create index if not exists proposals_date_idx on public.proposals(date desc);

alter table public.jobs
  add column if not exists proposal_id uuid references public.proposals(id) on delete set null;
create index if not exists jobs_proposal_idx on public.jobs(proposal_id);

alter table public.org_settings
  add column if not exists allow_tech_proposal_flag boolean not null default true;

alter table public.proposals enable row level security;
-- читают менеджер/админ; техник видит только пропозал, связанный с его работой
drop policy if exists prop_sel on public.proposals;
create policy prop_sel on public.proposals for select to authenticated
  using (
    public.my_role() in ('admin','manager')
    or exists (select 1 from public.jobs j
               where j.proposal_id = proposals.id and public.can_view_job(j.id))
  );
drop policy if exists prop_ins on public.proposals;
create policy prop_ins on public.proposals for insert to authenticated
  with check (public.my_role() in ('admin','manager'));
drop policy if exists prop_upd on public.proposals;
create policy prop_upd on public.proposals for update to authenticated
  using (public.my_role() in ('admin','manager'))
  with check (public.my_role() in ('admin','manager'));
drop policy if exists prop_del on public.proposals;
create policy prop_del on public.proposals for delete to authenticated
  using (public.my_role() = 'admin');

-- Связь инвойс↔пропозал ставит менеджер/админ. RLS менеджеру писать в jobs
-- не даёт, а открывать политику целиком опасно — функция меняет ровно
-- одно поле и фиксирует действие в журнале документов.
create or replace function public.link_job_proposal(p_job uuid, p_prop uuid)
returns void language plpgsql security definer set search_path = public as $$
declare v_unit text; v_no bigint; v_name text;
begin
  if public.my_role() not in ('admin','manager') then raise exception 'FORBIDDEN'; end if;
  if p_prop is not null then
    select no into v_no from public.proposals where id = p_prop;
    if v_no is null then raise exception 'NO_PROPOSAL'; end if;
  end if;
  update public.jobs
     set proposal_id  = p_prop,
         has_proposal = case when p_prop is not null then true else has_proposal end,
         updated_at   = now()
   where id = p_job
   returning unit_number into v_unit;
  if not found then raise exception 'NOT_FOUND'; end if;
  select display_name into v_name from public.profiles where id = auth.uid();
  insert into public.audit_log (actor, actor_name, action, entity, entity_id, details)
  values (auth.uid(), coalesce(v_name,''),
          case when p_prop is null then 'proposal_unlink' else 'proposal_link' end,
          'job', p_job::text,
          jsonb_build_object('unit', coalesce(v_unit,''), 'no', v_no));
end $$;
revoke all on function public.link_job_proposal(uuid, uuid) from public, anon;
grant execute on function public.link_job_proposal(uuid, uuid) to authenticated;

-- ---------------------------------------------------------------------
-- 2. ЖУРНАЛ: отдельная таблица для системных событий (tech_log).
--    Документные остаются в audit_log. Существующие системные записи
--    переносятся один раз (атомарно: перенос = удаление + вставка).
-- ---------------------------------------------------------------------
create table if not exists public.tech_log (
  id         uuid primary key default gen_random_uuid(),
  at         timestamptz not null default now(),
  actor      uuid,
  actor_name text not null default '',
  action     text not null,
  entity     text,
  entity_id  text,
  details    jsonb not null default '{}'::jsonb
);
create index if not exists tech_log_at_idx     on public.tech_log(at desc);
create index if not exists tech_log_action_idx on public.tech_log(action, at desc);

alter table public.tech_log enable row level security;
drop policy if exists tlog_ins on public.tech_log;
create policy tlog_ins on public.tech_log for insert to authenticated
  with check (actor = auth.uid());
drop policy if exists tlog_sel on public.tech_log;
create policy tlog_sel on public.tech_log for select to authenticated
  using (public.my_role() = 'admin');
-- политик update/delete нет — журнал неизменяем, как и audit_log

with moved as (
  delete from public.audit_log
  where action in ('user_register','user_create','user_block','user_unblock','role_change',
                   'password_change','password_reset','car_no_set','org_toggle','org_set',
                   'stock_set','backup_export','backup_restore')
  returning at, actor, actor_name, action, entity, entity_id, details
)
insert into public.tech_log (at, actor, actor_name, action, entity, entity_id, details)
select at, actor, actor_name, action, entity, entity_id, details from moved;

-- регистрация пользователя — системное событие: триггер пишет в tech_log
create or replace function public.log_new_profile()
returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if current_setting('techlog.restore', true) = '1' then
    return new;                                   -- идёт восстановление из бэкапа
  end if;
  insert into public.tech_log (actor, actor_name, action, entity, entity_id, details)
  values (new.id, new.display_name, 'user_register', 'profile', new.id::text,
          jsonb_build_object('login', new.login, 'role', new.role));
  return new;
end $$;

-- ---------------------------------------------------------------------
-- 3. СОГЛАСОВАНИЕ ПРОДЛЕНИЙ сверх лимита.
--    Техник создаёт заявку (insert под своим именем), менеджер/админ
--    решает через RPC; при одобрении продление применяется СЕРВЕРОМ
--    той же логикой, что и обычное продление (ext_of / superseded).
-- ---------------------------------------------------------------------
create table if not exists public.ext_requests (
  id           uuid primary key default gen_random_uuid(),
  job_id       uuid not null references public.jobs(id) on delete cascade,
  requested_by uuid not null references public.profiles(id) on delete cascade,
  requested_at timestamptz not null default now(),
  days         int  not null check (days between 1 and 60),
  qty_total    int  not null default 0,
  payload      jsonb not null default '[]'::jsonb,   -- [{id: placement_id, qty: n}]
  unit         text not null default '',
  cx           text not null default '',
  eq           text not null default '',
  status       text not null default 'pending'
               check (status in ('pending','approved','rejected')),
  decided_by   uuid references public.profiles(id) on delete set null,
  decided_at   timestamptz
);
create index if not exists extreq_status_idx on public.ext_requests(status, requested_at desc);
create index if not exists extreq_job_idx    on public.ext_requests(job_id);

alter table public.ext_requests enable row level security;
drop policy if exists exr_ins on public.ext_requests;
create policy exr_ins on public.ext_requests for insert to authenticated
  with check (requested_by = auth.uid());
drop policy if exists exr_sel on public.ext_requests;
create policy exr_sel on public.ext_requests for select to authenticated
  using (requested_by = auth.uid() or public.my_role() in ('admin','manager'));
drop policy if exists exr_del on public.ext_requests;
create policy exr_del on public.ext_requests for delete to authenticated
  using (public.my_role() = 'admin');
-- update только через RPC ниже

create or replace function public.decide_ext_request(p_id uuid, p_ok boolean)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_req  public.ext_requests%rowtype;
  v_pl   public.placements%rowtype;
  v_row  jsonb;
  v_q    int;
  v_base date;
  v_made int := 0;
  v_name text;
begin
  if public.my_role() not in ('admin','manager') then raise exception 'FORBIDDEN'; end if;

  select * into v_req from public.ext_requests
   where id = p_id and status = 'pending' for update;
  if not found then raise exception 'NOT_FOUND'; end if;

  select display_name into v_name from public.profiles where id = auth.uid();

  if not p_ok then
    update public.ext_requests
       set status = 'rejected', decided_by = auth.uid(), decided_at = now()
     where id = p_id;
    insert into public.audit_log (actor, actor_name, action, entity, entity_id, details)
    values (auth.uid(), coalesce(v_name,''), 'ext_request_rejected', 'job', v_req.job_id::text,
            jsonb_build_object('unit', v_req.unit, 'days', v_req.days, 'eq', v_req.eq));
    return;
  end if;

  for v_row in select * from jsonb_array_elements(v_req.payload) loop
    select * into v_pl from public.placements
     where id = (v_row->>'id')::uuid
       and job_id = v_req.job_id
       and picked_up = false
       and coalesce(superseded, false) = false
     for update;
    if not found then continue; end if;

    v_q := least(coalesce((v_row->>'qty')::int, 0), coalesce(v_pl.qty, 0));
    if v_q <= 0 then continue; end if;
    v_base := greatest(v_pl.due_date, current_date);

    insert into public.placements (
      id, job_id, equipment_type_id, qty, days, placed_date, due_date,
      picked_up, picked_up_at, picked_up_by, ext_of, superseded, superseded_at,
      technician_id, complex_id, counterparty_id, unit_number)
    values (
      gen_random_uuid(), v_pl.job_id, v_pl.equipment_type_id, v_q, v_req.days,
      v_base, v_base + v_req.days,
      false, null, null, v_pl.id, false, null,
      v_pl.technician_id, v_pl.complex_id, v_pl.counterparty_id, v_pl.unit_number);

    if v_q >= coalesce(v_pl.qty, 0) then
      update public.placements
         set superseded = true, superseded_at = now() where id = v_pl.id;
    else
      update public.placements set qty = v_pl.qty - v_q where id = v_pl.id;
    end if;
    v_made := v_made + v_q;
  end loop;

  update public.ext_requests
     set status = 'approved', decided_by = auth.uid(), decided_at = now()
   where id = p_id;

  insert into public.audit_log (actor, actor_name, action, entity, entity_id, details)
  values (auth.uid(), coalesce(v_name,''), 'ext_request_approved', 'job', v_req.job_id::text,
          jsonb_build_object('unit', v_req.unit, 'days', v_req.days, 'qty', v_made, 'eq', v_req.eq));
  if v_made > 0 then
    insert into public.audit_log (actor, actor_name, action, entity, entity_id, details)
    values (auth.uid(), coalesce(v_name,''), 'extension_create', 'job', v_req.job_id::text,
            jsonb_build_object('unit', v_req.unit, 'days', v_req.days, 'qty', v_made));
  end if;
end $$;
revoke all on function public.decide_ext_request(uuid, boolean) from public, anon;
grant execute on function public.decide_ext_request(uuid, boolean) to authenticated;
